"""模拟案例模拟数据集。

从 related_party_check.py 提取，供演示和测试使用。
"""

from typing import Tuple, List, Dict


def build_fixture() -> Tuple[dict, List[dict]]:
    """构建模拟案例模拟数据集（8家隐性关联方 + 1个干扰项）。

    返回: (审计方数据, [目标企业列表])
    """
    audit = {
        "name": "辰星科技股份有限公司",
        "shareholders": ["张某某(30%)", "李某某(25%)", "辰星控股有限公司(45%)"],
        "actual_controller": "张某某",
        "executives": ["张某某(董事长)", "王某某(总经理)", "赵某(监事)"],
        "legal_rep": "张某某",
        "address": "天津市滨海新区经济技术开发区信环西路20号",
        "phone": "022-5988****",
        "email": "info@demo-tech.example.com",
    }

    targets = [
        {
            "name": "星海贸易有限公司",
            "shareholders": ["王某(60%)", "李某(40%)"],
            "actual_controller": "王某",
            "executives": ["王某(执行董事)", "李某(经理)", "赵某(监事)"],
            "legal_rep": "王某",
            "historical_legal_reps": [],
            "address": "天津市滨海新区塘沽街道新港路100号",
            "phone": "138****5678",
            "email": "company1@demo-trade.example.com",
            "change_dates": [],
            "insured_employees": 5,
            "transaction_amount": 5000000,
        },
        {
            "name": "锦程科技有限公司",
            "shareholders": ["梁某(50%)", "陈某(50%)"],
            "actual_controller": "梁某",
            "executives": ["梁某(执行董事)", "王某某(经理)"],
            "legal_rep": "梁某",
            "historical_legal_reps": [],
            "address": "天津市南开区鞍山西道200号",
            "phone": "022-8790****",
            "email": "company2@demo-abc.example.com",
            "change_dates": [],
            "insured_employees": 8,
            "transaction_amount": 8500000,
        },
        {
            "name": "锦程信息咨询有限公司",
            "shareholders": ["梁某(40%)", "张某(30%)", "赵某(30%)"],
            "actual_controller": "梁某",
            "executives": ["梁某(执行董事)", "张某(经理)"],
            "legal_rep": "梁某",
            "historical_legal_reps": [],
            "address": "天津市南开区鞍山西道210号",
            "phone": "022-8791****",
            "email": "company2_info@demo-abc.example.com",
            "change_dates": [],
            "insured_employees": 3,
            "transaction_amount": 3200000,
        },
        {
            "name": "辰创商贸有限公司",
            "shareholders": ["刘某(100%)"],
            "actual_controller": "刘某",
            "executives": ["刘某(执行董事)", "孙某(监事)"],
            "legal_rep": "刘某",
            "historical_legal_reps": [],
            "address": "天津市滨海新区经济技术开发区信环西路18号",
            "phone": "022-5900****",
            "email": "company4@demo-zhuoc.example.com",
            "change_dates": [],
            "insured_employees": 2,
            "transaction_amount": 1800000,
        },
        {
            "name": "星辉科技有限公司",
            "shareholders": ["周某(70%)", "吴某(30%)"],
            "actual_controller": "周某",
            "executives": ["周某(执行董事)", "吴某(监事)"],
            "legal_rep": "周某",
            "historical_legal_reps": [],
            "address": "天津市西青区中北镇星光路50号",
            "phone": "138****5678",
            "email": "company5@demo-tech.example.com",
            "change_dates": [],
            "insured_employees": 4,
            "transaction_amount": 4200000,
        },
        {
            "name": "汇鑫信息技术有限公司",
            "shareholders": ["陈某(55%)", "黄某(45%)"],
            "actual_controller": "陈某",
            "executives": ["陈某(执行董事)", "黄某(经理)"],
            "legal_rep": "陈某",
            "historical_legal_reps": ["赵某"],
            "address": "天津市河东区十一经路80号",
            "phone": "022-2410****",
            "email": "company6@demo-info.example.com",
            "change_dates": [],
            "insured_employees": 1,
            "transaction_amount": 1200000,
        },
        {
            "name": "北辰区锐达科技有限公司",
            "shareholders": ["张某某(80%)", "林某(20%)"],
            "actual_controller": "张某某",
            "executives": ["张某某(执行董事)", "林某(监事)"],
            "legal_rep": "张某某",
            "historical_legal_reps": [],
            "address": "天津市北辰区京津公路300号",
            "phone": "022-2680****",
            "email": "company7@demo-bc.example.com",
            "change_dates": [],
            "insured_employees": 0,
            "transaction_amount": 9500000,
        },
        {
            "name": "辰研咨询有限公司",
            "shareholders": ["辰星控股有限公司(51%)", "侯某(49%)"],
            "actual_controller": "张某某",
            "executives": ["侯某(执行董事)", "侯某(经理)"],
            "legal_rep": "侯某",
            "historical_legal_reps": [],
            "address": "天津市和平区南京路100号",
            "phone": "022-2330****",
            "email": "company8@demo-tj.example.com",
            "change_dates": [],
            "insured_employees": 6,
            "transaction_amount": 7200000,
        },
        {
            "name": "通用企业股份有限公司",
            "shareholders": ["深圳市地铁集团有限公司(27.91%)", "香港中央结算有限公司(7.34%)", "郁某(0.08%)"],
            "actual_controller": "深圳市地铁集团有限公司",
            "executives": ["郁某(董事长)", "祝某(总裁)", "韩某(执行副总裁)"],
            "legal_rep": "郁某",
            "historical_legal_reps": [],
            "address": "深圳市盐田区大梅沙环梅路33号集团总部",
            "phone": "0755-2560****",
            "email": "ir@demo-corp.example.com",
            "change_dates": [],
            "insured_employees": 10000,
            "transaction_amount": 500000000,
        },
    ]

    return audit, targets
